language: r
cache: packages
r:
- release
warnings_are_errors: true
before_install:
 - sudo apt-get -y install libharfbuzz-dev libfribidi-dev
 - sudo apt-get -y install libsodium-dev
 - Rscript -e 'remotes::install_cran("textshaping"); remotes::install_cran("pkgdown")'
r_packages:
- rmarkdown

env:
  global:
  - MAKE="make -j 2"
  - GIT_BRANCH="${TRAVIS_BRANCH}"
  - secure: "WS8+VK5iOC3G20TPGSoFJk6I1UhaTCY3ZZW/MDSmYFepRyNWNYLqhP8vJCp72xwjVLafNXTTKvOk2FViUbAhnuu1gWLd2p7UgHwMadrOErNRaJQDsJRKnOAhTsUUaJds5OiVgb6PwvDQB7wlrewKnongNRL3sl/14iTWLYcyJ6liqPU3kkkpfWcOax4594w0asseTI2NbHnF3myUoLrkONkU+vMZAVlLEPhR6JMo3z4F2STV+jR3yHgbcYaSSnVA3mhy1DmFKb299PRL7TSqnkybw2T8nyJBvGGMvC46m4V+Cgg5biUXDlveHwsZYWeK1dyOBKHUyItYiun+k1znwbbd+SriYCSlb+EzLfI2CckGTMLuu9SLUc4J4LlBOlG+LKWbYijBtFs/RXhEDaLREH7vNh7tuHxozQWwQI8tKpj06gL/M85NBf1pLna3uRRl4BRJIMGxRMRxEceuz0p+22Sps9UkBNzET1cRlqR/6QE3b27OOX3JtaNaPn9vUE/6693zDKMTIlv5kMWd7Vxf96bBVfr+jqxrWHTeKl47mSHm99UVk2qxggB5QY/M7UYqkPsIFHlxIW0HgPDfhZydDja4J1/UdqEOZJauZu26OBu9u1m3Q+uA77KwbAIlF+b854ZbK/sNXJTw1ssasmHlD2mnFj6lSlzGvMsGsbjxZCw="

branches:
  only:
  - main
  - "/^release\\/v?[\\d\\.]+$/"

stages:
- name: Check
  if: commit_message != "Re-build README.Rmd"
- name: "Extended checks"
  if: commit_message != "Re-build README.Rmd" AND branch != main


jobs:
- stage: Check
  after_success:
  - R CMD INSTALL .
  - git pull
  - git checkout ${TRAVIS_BRANCH}
  - Rscript -e 'rmarkdown::render("README.Rmd")'
  - git config --local user.email "ci@travis-ci.com"
  - git config --local user.name "Travis CI"
  - git add README.md || echo "Nothing added"
  - git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
  - git remote add originpush "https://${GITHUB_PAK}@github.com/${TRAVIS_REPO_SLUG}"
  - git push --set-upstream originpush ${TRAVIS_BRANCH} || echo "No changes to push"
  before_deploy:
  - Rscript -e 'pkgdown::build_site()'
  deploy:
    edge: true
    provider: pages
    token: ${GITHUB_PAK}
    keep_history: true
    local_dir: docs
    on:
      branch: main
- stage: "Extended checks"
  name: R-devel
  r: devel
- stage: "Extended checks"
  name: R-oldrel
  r: oldrel
